/**
 * =============================================================
 * AetherCore-Web3 | /frontend-react/src/contexts/Web3Context.jsx
 * Author  : AetherCore Team
 * Version : 1.0.0
 * Date    : 2026-03-12
 * =============================================================
 *
 * PURPOSE:
 * Global React Context that owns ALL blockchain state for the
 * AetherCore user portal. Any component that needs wallet info,
 * contract instances, or chain verification can call:
 *
 * const { address, coreContract, tokenContract, ... } = useWeb3();
 *
 * WHAT THIS CONTEXT MANAGES:
 * ┌───────────────────────────────────────────────────────────┐
 * │ • MetaMask connection / disconnection                     │
 * │ • Wallet address + ENS-like display                       │
 * │ • Chain ID tracking + Sepolia/Localhost enforcement       │
 * │ • Ethers.js BrowserProvider + Signer instantiation        │
 * │ • Read-only CoreProtocol contract (provider)             │
 * │ • Write CoreProtocol contract (signer)                    │
 * │ • Read-only AntiGravityToken contract (provider)         │
 * │ • Write AntiGravityToken contract (signer)                │
 * └───────────────────────────────────────────────────────────┘
 *
 * ETHERS v6 NOTE:
 * ethers v6 changed several APIs from v5:
 * - `new ethers.providers.Web3Provider` → `new ethers.BrowserProvider`
 * - `provider.getSigner()` is now async (returns Promise<Signer>)
 * - `ethers.utils.formatEther` → `ethers.formatEther`
 * - `ethers.BigNumber.from` → direct `BigInt` or `ethers.parseEther`
 *
 * ABI FILES:
 * Place compiled ABIs from Hardhat artifacts here:
 * /frontend-react/src/abi/CoreProtocol.json
 * /frontend-react/src/abi/AntiGravityToken.json
 * Export them as: { abi: [...] }
 *
 * CONTRACT ADDRESSES:
 * Imported from the deployment output written by deploy.js:
 * /blockchain/deployments/sepolia.json   (production)
 * /blockchain/deployments/localhost.json (development)
 * =============================================================
 */

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';
import { ethers } from 'ethers';

// ── ABI Imports ────────────────────────────────────────────────────────────────
// These JSON files are auto-generated by Hardhat during `npx hardhat compile`.
// Copy them from /blockchain/artifacts/contracts/<Name>.sol/<Name>.json
import CoreProtocolArtifact from '../abi/CoreProtocol.json';
import AntiGravityTokenArtifact from '../abi/AntiGravityToken.json';

// ── Deployment Address Fallback ────────────────────────────────────────────────
// In a real setup, import from the deployment JSON based on chainId.
// These are overridden by env variables or the deployment file at runtime.
// ── Deployment Address Fallback ────────────────────────────────────────────────
const CONTRACT_ADDRESSES = {
  // Sepolia  (chainId: 11155111)
  11155111: {
    coreProtocol: import.meta.env.VITE_SEPOLIA_CORE_ADDRESS || '',
    antiGravityToken: import.meta.env.VITE_SEPOLIA_TOKEN_ADDRESS || '',
  },
  // Localhost (Hardhat default: 31337)
  31337: {
    coreProtocol: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
    antiGravityToken: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
  },
  // Localhost (MetaMask default: 1337)
  1337: {
    coreProtocol: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
    antiGravityToken: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
  },
};

// Chains we accept. Any other chain will trigger a "switch network" prompt.
const SUPPORTED_CHAIN_IDS = [11155111, 31337, 1337];

// ── Context Definition ─────────────────────────────────────────────────────────

/**
 * @typedef {Object} Web3ContextValue
 * @property {string|null}               address          - Connected wallet address (checksummed).
 * @property {string}                    shortAddress     - Truncated address for display (0x1234...abcd).
 * @property {number|null}               chainId          - Current EVM chain ID.
 * @property {boolean}                   isConnected      - True if a wallet is connected.
 * @property {boolean}                   isCorrectNetwork - True if on a supported network.
 * @property {boolean}                   isConnecting     - True while connection is in progress.
 * @property {string|null}               error            - Last connection/network error message.
 * @property {ethers.Contract|null}      coreRead         - CoreProtocol read-only instance.
 * @property {ethers.Contract|null}      coreWrite        - CoreProtocol write instance (signer).
 * @property {ethers.Contract|null}      tokenRead        - AntiGravityToken read-only instance.
 * @property {ethers.Contract|null}      tokenWrite       - AntiGravityToken write instance (signer).
 * @property {Function}                  connectWallet    - Triggers MetaMask connection flow.
 * @property {Function}                  disconnectWallet - Clears local wallet state.
 * @property {Function}                  switchNetwork    - Prompts user to switch to Sepolia.
 */
const Web3Context = createContext(null);

// ── Provider Component ─────────────────────────────────────────────────────────

/**
 * @component Web3Provider
 * @description Wraps the entire application with blockchain connectivity state.
 * Place this at the root of your component tree in App.jsx.
 *
 * @param {React.ReactNode} children
 */
export function Web3Provider({ children }) {
  // ── Core State ─────────────────────────────────────────────────────────────
  const [address, setAddress] = useState(null);
  const [chainId, setChainId] = useState(null);
  const [provider, setProvider] = useState(null);   // ethers.BrowserProvider
  const [signer, setSigner] = useState(null);   // ethers.Signer
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState(null);

  // ── Derived Values ─────────────────────────────────────────────────────────
  const isConnected = !!address;
  const isCorrectNetwork = SUPPORTED_CHAIN_IDS.includes(chainId);

  /** Truncates wallet address for display: "0x1234...abcd" */
  const shortAddress = useMemo(() => {
    if (!address) return '';
    return `${address.slice(0, 6)}...${address.slice(-4)}`;
  }, [address]);

  // ── Contract Addresses (resolved per chain) ────────────────────────────────
  const contractAddresses = useMemo(() => {
    return CONTRACT_ADDRESSES[chainId] || null;
  }, [chainId]);

  // ── Read-only Contract Instances (provider — no gas, no MetaMask) ──────────
  // Created from a JsonRpcProvider so they work even without a wallet connected.
  const coreRead = useMemo(() => {
    if (!provider || !contractAddresses?.coreProtocol) return null;
    return new ethers.Contract(
      contractAddresses.coreProtocol,
      CoreProtocolArtifact.abi,
      provider
    );
  }, [provider, contractAddresses]);

  const tokenRead = useMemo(() => {
    if (!provider || !contractAddresses?.antiGravityToken) return null;
    return new ethers.Contract(
      contractAddresses.antiGravityToken,
      AntiGravityTokenArtifact.abi,
      provider
    );
  }, [provider, contractAddresses]);

  // ── Write Contract Instances (signer — requires MetaMask approval) ─────────
  const coreWrite = useMemo(() => {
    if (!signer || !contractAddresses?.coreProtocol) return null;
    return new ethers.Contract(
      contractAddresses.coreProtocol,
      CoreProtocolArtifact.abi,
      signer
    );
  }, [signer, contractAddresses]);

  const tokenWrite = useMemo(() => {
    if (!signer || !contractAddresses?.antiGravityToken) return null;
    return new ethers.Contract(
      contractAddresses.antiGravityToken,
      AntiGravityTokenArtifact.abi,
      signer
    );
  }, [signer, contractAddresses]);

  // ── Internal: Initialize provider + signer from window.ethereum ───────────
  const initializeProvider = useCallback(async () => {
    if (!window.ethereum) return;

    // ethers v6: BrowserProvider wraps window.ethereum
    const browserProvider = new ethers.BrowserProvider(window.ethereum);
    setProvider(browserProvider);

    const network = await browserProvider.getNetwork();
    setChainId(Number(network.chainId));

    const accounts = await browserProvider.listAccounts();
    if (accounts.length > 0) {
      const ethSigner = await browserProvider.getSigner();
      setSigner(ethSigner);
      setAddress(await ethSigner.getAddress());
    }
  }, []);

  // ── Connect Wallet ─────────────────────────────────────────────────────────
  /**
   * Triggers the MetaMask connection popup and initializes all state.
   * Safe to call multiple times — MetaMask deduplicates the popup.
   */
  const connectWallet = useCallback(async () => {
    if (!window.ethereum) {
      setError('MetaMask is not installed. Please install it from metamask.io');
      return;
    }
    setIsConnecting(true);
    setError(null);
    try {
      // eth_requestAccounts triggers the MetaMask connection modal
      await window.ethereum.request({ method: 'eth_requestAccounts' });
      await initializeProvider();
    } catch (err) {
      // Error code 4001 = user rejected the connection request
      if (err.code === 4001) {
        setError('Connection rejected. Please accept the MetaMask prompt to continue.');
      } else {
        setError(err.message || 'An unknown error occurred during wallet connection.');
      }
    } finally {
      setIsConnecting(false);
    }
  }, [initializeProvider]);

  // ── Disconnect Wallet ──────────────────────────────────────────────────────
  /**
   * Clears all local wallet state. Note: this does NOT revoke MetaMask's
   * site permissions — that requires the user to do so in MetaMask settings.
   */
  const disconnectWallet = useCallback(() => {
    setAddress(null);
    setChainId(null);
    setProvider(null);
    setSigner(null);
    setError(null);
  }, []);

  // ── Switch Network ─────────────────────────────────────────────────────────
  /**
   * Prompts the user to switch to Sepolia testnet.
   * If Sepolia is not in their MetaMask, it will be added automatically.
   */
  const switchNetwork = useCallback(async () => {
    if (!window.ethereum) return;
    try {
      await window.ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: '0xaa36a7' }], // 0xaa36a7 = 11155111 (Sepolia)
      });
    } catch (switchError) {
      // Error code 4902 = chain not added to MetaMask yet — add it
      if (switchError.code === 4902) {
        await window.ethereum.request({
          method: 'wallet_addEthereumChain',
          params: [{
            chainId: '0xaa36a7',
            chainName: 'Sepolia Testnet',
            nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
            rpcUrls: ['https://rpc.sepolia.org'],
            blockExplorerUrls: ['https://sepolia.etherscan.io'],
          }],
        });
      } else {
        setError('Failed to switch network: ' + switchError.message);
      }
    }
  }, []);

  // ── MetaMask Event Listeners ───────────────────────────────────────────────
  // Listen for account and chain changes OUTSIDE of our app's control
  // (e.g., user switches accounts in MetaMask directly).
  useEffect(() => {
    if (!window.ethereum) return;

    const handleAccountsChanged = async (accounts) => {
      if (accounts.length === 0) {
        // User disconnected all accounts in MetaMask
        disconnectWallet();
      } else {
        // User switched accounts — re-initialize with the new account
        await initializeProvider();
      }
    };

    const handleChainChanged = () => {
      // MetaMask recommends a full page reload on chain change to avoid
      // stale provider state bugs.
      window.location.reload();
    };

    window.ethereum.on('accountsChanged', handleAccountsChanged);
    window.ethereum.on('chainChanged', handleChainChanged);

    // Auto-connect if the user previously authorized this site
    initializeProvider();

    // Cleanup listeners on unmount
    return () => {
      window.ethereum.removeListener('accountsChanged', handleAccountsChanged);
      window.ethereum.removeListener('chainChanged', handleChainChanged);
    };
  }, [initializeProvider, disconnectWallet]);

  // ── Context Value ──────────────────────────────────────────────────────────
  const value = useMemo(() => ({
    address,
    shortAddress,
    chainId,
    isConnected,
    isCorrectNetwork,
    isConnecting,
    error,
    provider,
    signer,
    coreRead,
    coreWrite,
    tokenRead,
    tokenWrite,
    connectWallet,
    disconnectWallet,
    switchNetwork,
  }), [
    address, shortAddress, chainId, isConnected, isCorrectNetwork,
    isConnecting, error, provider, signer,
    coreRead, coreWrite, tokenRead, tokenWrite,
    connectWallet, disconnectWallet, switchNetwork,
  ]);

  return (
    <Web3Context.Provider value={value}>
      {children}
    </Web3Context.Provider>
  );
}

// ── Custom Hook ────────────────────────────────────────────────────────────────

/**
 * @hook useWeb3
 * @description Consumes the Web3Context. Must be used inside a <Web3Provider>.
 * @returns {Web3ContextValue}
 *
 * @example
 * const { address, connectWallet, coreWrite } = useWeb3();
 */
export function useWeb3() {
  const ctx = useContext(Web3Context);
  if (!ctx) {
    throw new Error('useWeb3 must be used inside a <Web3Provider>. Did you wrap your app in App.jsx?');
  }
  return ctx;
}

export default Web3Context;